# Instructor Feedback for HW - 01
---

Dear Dr. Pan -- this is the feedback issue template for my assignment. Feel free to use this template as a way of providing me feedback and guidance based on my performance in this homework assignment.

---

### TASK 01 : `[_ / 1 credit(s)]`
#### Any Suggestions ?

### TASK 02 : `[_ / 2 credit(s)]`
#### Any Suggestions ?

### TASK 03 : `[_ / 2 credit(s)]`
#### Any Suggestions ?

### TASK 04 : `[_ / 1 credit(s)]`
#### Any Suggestions ?

### TASK 05 : `[_ / 2 credit(s)]`
#### Any Suggestions ?

### TASK 06 : `[_ / 2 credit(s)]`
#### Any Suggestions ?

### TOTAL   : `[_ / 10 credit(s)]`

## Late Penalty Clause
- [ ] On time: No Penalty
- [ ] Late, but next day (before noon): -10% of available points
- [ ] Late, but next day (after noon): -20% of available points
- [ ] Two days late or later: NO CREDIT.